version: '3'

services:
  coturn:
    image: instrumentisto/coturn
    network_mode: "host"

  backend:
    build:
      context: .
      dockerfile: signaler.Dockerfile
    ports:
      - "$SIGNALER_PORT:$SIGNALER_PORT"
    environment:
      - PORT:$SIGNALER_PORT

  frontend:
    image: patapatam/webrtc-chat-client:latest
    environment:
      - SIGNALER_HOST:$SIGNALER_HOST
      - SIGNALER_PORT:$SIGNALER_PORT
      - STUN_HOST:$STUN_HOST
      - STUN_PORT:$STUN_PORT
